// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/luqasn/go-pagerduty2/models"
)

// NewCreateOverrideParams creates a new CreateOverrideParams object
// with the default values initialized.
func NewCreateOverrideParams() *CreateOverrideParams {
	var ()
	return &CreateOverrideParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOverrideParamsWithTimeout creates a new CreateOverrideParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateOverrideParamsWithTimeout(timeout time.Duration) *CreateOverrideParams {
	var ()
	return &CreateOverrideParams{

		timeout: timeout,
	}
}

// NewCreateOverrideParamsWithContext creates a new CreateOverrideParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateOverrideParamsWithContext(ctx context.Context) *CreateOverrideParams {
	var ()
	return &CreateOverrideParams{

		Context: ctx,
	}
}

// NewCreateOverrideParamsWithHTTPClient creates a new CreateOverrideParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateOverrideParamsWithHTTPClient(client *http.Client) *CreateOverrideParams {
	var ()
	return &CreateOverrideParams{
		HTTPClient: client,
	}
}

/*CreateOverrideParams contains all the parameters to send to the API endpoint
for the create override operation typically these are written to a http.Request
*/
type CreateOverrideParams struct {

	/*ID*/
	ID string
	/*Override
	  The override to be created

	*/
	Override *models.CreateOverrideParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create override params
func (o *CreateOverrideParams) WithTimeout(timeout time.Duration) *CreateOverrideParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create override params
func (o *CreateOverrideParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create override params
func (o *CreateOverrideParams) WithContext(ctx context.Context) *CreateOverrideParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create override params
func (o *CreateOverrideParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create override params
func (o *CreateOverrideParams) WithHTTPClient(client *http.Client) *CreateOverrideParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create override params
func (o *CreateOverrideParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create override params
func (o *CreateOverrideParams) WithID(id string) *CreateOverrideParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create override params
func (o *CreateOverrideParams) SetID(id string) {
	o.ID = id
}

// WithOverride adds the override to the create override params
func (o *CreateOverrideParams) WithOverride(override *models.CreateOverrideParamsBody) *CreateOverrideParams {
	o.SetOverride(override)
	return o
}

// SetOverride adds the override to the create override params
func (o *CreateOverrideParams) SetOverride(override *models.CreateOverrideParamsBody) {
	o.Override = override
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOverrideParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Override != nil {
		if err := r.SetBodyParam(o.Override); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
