// Code generated by go-swagger; DO NOT EDIT.

package maintenance_windows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/luqasn/go-pagerduty2/models"
)

// NewPostMaintenanceWindowsParams creates a new PostMaintenanceWindowsParams object
// with the default values initialized.
func NewPostMaintenanceWindowsParams() *PostMaintenanceWindowsParams {
	var ()
	return &PostMaintenanceWindowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMaintenanceWindowsParamsWithTimeout creates a new PostMaintenanceWindowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMaintenanceWindowsParamsWithTimeout(timeout time.Duration) *PostMaintenanceWindowsParams {
	var ()
	return &PostMaintenanceWindowsParams{

		timeout: timeout,
	}
}

// NewPostMaintenanceWindowsParamsWithContext creates a new PostMaintenanceWindowsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMaintenanceWindowsParamsWithContext(ctx context.Context) *PostMaintenanceWindowsParams {
	var ()
	return &PostMaintenanceWindowsParams{

		Context: ctx,
	}
}

// NewPostMaintenanceWindowsParamsWithHTTPClient creates a new PostMaintenanceWindowsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMaintenanceWindowsParamsWithHTTPClient(client *http.Client) *PostMaintenanceWindowsParams {
	var ()
	return &PostMaintenanceWindowsParams{
		HTTPClient: client,
	}
}

/*PostMaintenanceWindowsParams contains all the parameters to send to the API endpoint
for the post maintenance windows operation typically these are written to a http.Request
*/
type PostMaintenanceWindowsParams struct {

	/*From
	  The email address of the user making the request.

	*/
	From strfmt.Email
	/*MaintenanceWindow
	  The maintenance window object.

	*/
	MaintenanceWindow *models.PostMaintenanceWindowsParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) WithTimeout(timeout time.Duration) *PostMaintenanceWindowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) WithContext(ctx context.Context) *PostMaintenanceWindowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) WithHTTPClient(client *http.Client) *PostMaintenanceWindowsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) WithFrom(from strfmt.Email) *PostMaintenanceWindowsParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) SetFrom(from strfmt.Email) {
	o.From = from
}

// WithMaintenanceWindow adds the maintenanceWindow to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) WithMaintenanceWindow(maintenanceWindow *models.PostMaintenanceWindowsParamsBody) *PostMaintenanceWindowsParams {
	o.SetMaintenanceWindow(maintenanceWindow)
	return o
}

// SetMaintenanceWindow adds the maintenanceWindow to the post maintenance windows params
func (o *PostMaintenanceWindowsParams) SetMaintenanceWindow(maintenanceWindow *models.PostMaintenanceWindowsParamsBody) {
	o.MaintenanceWindow = maintenanceWindow
}

// WriteToRequest writes these params to a swagger request
func (o *PostMaintenanceWindowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param From
	if err := r.SetHeaderParam("From", o.From.String()); err != nil {
		return err
	}

	if o.MaintenanceWindow != nil {
		if err := r.SetBodyParam(o.MaintenanceWindow); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
