// Code generated by go-swagger; DO NOT EDIT.

package log_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLogEntriesParams creates a new GetLogEntriesParams object
// with the default values initialized.
func NewGetLogEntriesParams() *GetLogEntriesParams {
	var (
		isOverviewDefault = bool(false)
		timeZoneDefault   = string("UTC")
	)
	return &GetLogEntriesParams{
		IsOverview: &isOverviewDefault,
		TimeZone:   &timeZoneDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogEntriesParamsWithTimeout creates a new GetLogEntriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLogEntriesParamsWithTimeout(timeout time.Duration) *GetLogEntriesParams {
	var (
		isOverviewDefault = bool(false)
		timeZoneDefault   = string("UTC")
	)
	return &GetLogEntriesParams{
		IsOverview: &isOverviewDefault,
		TimeZone:   &timeZoneDefault,

		timeout: timeout,
	}
}

// NewGetLogEntriesParamsWithContext creates a new GetLogEntriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLogEntriesParamsWithContext(ctx context.Context) *GetLogEntriesParams {
	var (
		isOverviewDefault = bool(false)
		timeZoneDefault   = string("UTC")
	)
	return &GetLogEntriesParams{
		IsOverview: &isOverviewDefault,
		TimeZone:   &timeZoneDefault,

		Context: ctx,
	}
}

// NewGetLogEntriesParamsWithHTTPClient creates a new GetLogEntriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLogEntriesParamsWithHTTPClient(client *http.Client) *GetLogEntriesParams {
	var (
		isOverviewDefault = bool(false)
		timeZoneDefault   = string("UTC")
	)
	return &GetLogEntriesParams{
		IsOverview: &isOverviewDefault,
		TimeZone:   &timeZoneDefault,
		HTTPClient: client,
	}
}

/*GetLogEntriesParams contains all the parameters to send to the API endpoint
for the get log entries operation typically these are written to a http.Request
*/
type GetLogEntriesParams struct {

	/*Include
	  Array of additional details to include.

	*/
	Include []string
	/*IsOverview
	  If `true`, will return a subset of log entries that show only the most important changes to the incident.

	*/
	IsOverview *bool
	/*Since
	  The start of the date range over which you want to search.

	*/
	Since *strfmt.DateTime
	/*TimeZone
	  Time zone in which dates in the result will be rendered.

	*/
	TimeZone *string
	/*Until
	  The end of the date range over which you want to search.

	*/
	Until *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get log entries params
func (o *GetLogEntriesParams) WithTimeout(timeout time.Duration) *GetLogEntriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get log entries params
func (o *GetLogEntriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get log entries params
func (o *GetLogEntriesParams) WithContext(ctx context.Context) *GetLogEntriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get log entries params
func (o *GetLogEntriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get log entries params
func (o *GetLogEntriesParams) WithHTTPClient(client *http.Client) *GetLogEntriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get log entries params
func (o *GetLogEntriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInclude adds the include to the get log entries params
func (o *GetLogEntriesParams) WithInclude(include []string) *GetLogEntriesParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the get log entries params
func (o *GetLogEntriesParams) SetInclude(include []string) {
	o.Include = include
}

// WithIsOverview adds the isOverview to the get log entries params
func (o *GetLogEntriesParams) WithIsOverview(isOverview *bool) *GetLogEntriesParams {
	o.SetIsOverview(isOverview)
	return o
}

// SetIsOverview adds the isOverview to the get log entries params
func (o *GetLogEntriesParams) SetIsOverview(isOverview *bool) {
	o.IsOverview = isOverview
}

// WithSince adds the since to the get log entries params
func (o *GetLogEntriesParams) WithSince(since *strfmt.DateTime) *GetLogEntriesParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get log entries params
func (o *GetLogEntriesParams) SetSince(since *strfmt.DateTime) {
	o.Since = since
}

// WithTimeZone adds the timeZone to the get log entries params
func (o *GetLogEntriesParams) WithTimeZone(timeZone *string) *GetLogEntriesParams {
	o.SetTimeZone(timeZone)
	return o
}

// SetTimeZone adds the timeZone to the get log entries params
func (o *GetLogEntriesParams) SetTimeZone(timeZone *string) {
	o.TimeZone = timeZone
}

// WithUntil adds the until to the get log entries params
func (o *GetLogEntriesParams) WithUntil(until *strfmt.DateTime) *GetLogEntriesParams {
	o.SetUntil(until)
	return o
}

// SetUntil adds the until to the get log entries params
func (o *GetLogEntriesParams) SetUntil(until *strfmt.DateTime) {
	o.Until = until
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogEntriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesInclude := o.Include

	joinedInclude := swag.JoinByFormat(valuesInclude, "multi")
	// query array param include[]
	if err := r.SetQueryParam("include[]", joinedInclude...); err != nil {
		return err
	}

	if o.IsOverview != nil {

		// query param is_overview
		var qrIsOverview bool
		if o.IsOverview != nil {
			qrIsOverview = *o.IsOverview
		}
		qIsOverview := swag.FormatBool(qrIsOverview)
		if qIsOverview != "" {
			if err := r.SetQueryParam("is_overview", qIsOverview); err != nil {
				return err
			}
		}

	}

	if o.Since != nil {

		// query param since
		var qrSince strfmt.DateTime
		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := qrSince.String()
		if qSince != "" {
			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}

	}

	if o.TimeZone != nil {

		// query param time_zone
		var qrTimeZone string
		if o.TimeZone != nil {
			qrTimeZone = *o.TimeZone
		}
		qTimeZone := qrTimeZone
		if qTimeZone != "" {
			if err := r.SetQueryParam("time_zone", qTimeZone); err != nil {
				return err
			}
		}

	}

	if o.Until != nil {

		// query param until
		var qrUntil strfmt.DateTime
		if o.Until != nil {
			qrUntil = *o.Until
		}
		qUntil := qrUntil.String()
		if qUntil != "" {
			if err := r.SetQueryParam("until", qUntil); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
