// Code generated by go-swagger; DO NOT EDIT.

package extension_schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new extension schemas API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for extension schemas API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetExtensionSchemas lists extension schemas

List all extension schemas.
*/
func (a *Client) GetExtensionSchemas(params *GetExtensionSchemasParams, authInfo runtime.ClientAuthInfoWriter) (*GetExtensionSchemasOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetExtensionSchemasParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetExtensionSchemas",
		Method:             "GET",
		PathPattern:        "/extension_schemas",
		ProducesMediaTypes: []string{"application/vnd.pagerduty+json;version=2"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetExtensionSchemasReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetExtensionSchemasOK), nil

}

/*
GetExtensionSchemasID gets an extension vendor

Get details about one specific extension vendor.
*/
func (a *Client) GetExtensionSchemasID(params *GetExtensionSchemasIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetExtensionSchemasIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetExtensionSchemasIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetExtensionSchemasID",
		Method:             "GET",
		PathPattern:        "/extension_schemas/{id}",
		ProducesMediaTypes: []string{"application/vnd.pagerduty+json;version=2"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetExtensionSchemasIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetExtensionSchemasIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
