// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/luqasn/go-pagerduty2/models"
)

// NewCreateContactMethodParams creates a new CreateContactMethodParams object
// with the default values initialized.
func NewCreateContactMethodParams() *CreateContactMethodParams {
	var ()
	return &CreateContactMethodParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateContactMethodParamsWithTimeout creates a new CreateContactMethodParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateContactMethodParamsWithTimeout(timeout time.Duration) *CreateContactMethodParams {
	var ()
	return &CreateContactMethodParams{

		timeout: timeout,
	}
}

// NewCreateContactMethodParamsWithContext creates a new CreateContactMethodParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateContactMethodParamsWithContext(ctx context.Context) *CreateContactMethodParams {
	var ()
	return &CreateContactMethodParams{

		Context: ctx,
	}
}

// NewCreateContactMethodParamsWithHTTPClient creates a new CreateContactMethodParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateContactMethodParamsWithHTTPClient(client *http.Client) *CreateContactMethodParams {
	var ()
	return &CreateContactMethodParams{
		HTTPClient: client,
	}
}

/*CreateContactMethodParams contains all the parameters to send to the API endpoint
for the create contact method operation typically these are written to a http.Request
*/
type CreateContactMethodParams struct {

	/*ContactMethod
	  The contact method to be created.

	*/
	ContactMethod *models.CreateContactMethodParamsBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create contact method params
func (o *CreateContactMethodParams) WithTimeout(timeout time.Duration) *CreateContactMethodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create contact method params
func (o *CreateContactMethodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create contact method params
func (o *CreateContactMethodParams) WithContext(ctx context.Context) *CreateContactMethodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create contact method params
func (o *CreateContactMethodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create contact method params
func (o *CreateContactMethodParams) WithHTTPClient(client *http.Client) *CreateContactMethodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create contact method params
func (o *CreateContactMethodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContactMethod adds the contactMethod to the create contact method params
func (o *CreateContactMethodParams) WithContactMethod(contactMethod *models.CreateContactMethodParamsBody) *CreateContactMethodParams {
	o.SetContactMethod(contactMethod)
	return o
}

// SetContactMethod adds the contactMethod to the create contact method params
func (o *CreateContactMethodParams) SetContactMethod(contactMethod *models.CreateContactMethodParamsBody) {
	o.ContactMethod = contactMethod
}

// WithID adds the id to the create contact method params
func (o *CreateContactMethodParams) WithID(id string) *CreateContactMethodParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create contact method params
func (o *CreateContactMethodParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateContactMethodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContactMethod != nil {
		if err := r.SetBodyParam(o.ContactMethod); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
