// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContactMethodParams creates a new GetContactMethodParams object
// with the default values initialized.
func NewGetContactMethodParams() *GetContactMethodParams {
	var ()
	return &GetContactMethodParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContactMethodParamsWithTimeout creates a new GetContactMethodParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContactMethodParamsWithTimeout(timeout time.Duration) *GetContactMethodParams {
	var ()
	return &GetContactMethodParams{

		timeout: timeout,
	}
}

// NewGetContactMethodParamsWithContext creates a new GetContactMethodParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContactMethodParamsWithContext(ctx context.Context) *GetContactMethodParams {
	var ()
	return &GetContactMethodParams{

		Context: ctx,
	}
}

// NewGetContactMethodParamsWithHTTPClient creates a new GetContactMethodParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContactMethodParamsWithHTTPClient(client *http.Client) *GetContactMethodParams {
	var ()
	return &GetContactMethodParams{
		HTTPClient: client,
	}
}

/*GetContactMethodParams contains all the parameters to send to the API endpoint
for the get contact method operation typically these are written to a http.Request
*/
type GetContactMethodParams struct {

	/*ContactMethodID
	  The contact method ID on the user.

	*/
	ContactMethodID string
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get contact method params
func (o *GetContactMethodParams) WithTimeout(timeout time.Duration) *GetContactMethodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get contact method params
func (o *GetContactMethodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get contact method params
func (o *GetContactMethodParams) WithContext(ctx context.Context) *GetContactMethodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get contact method params
func (o *GetContactMethodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get contact method params
func (o *GetContactMethodParams) WithHTTPClient(client *http.Client) *GetContactMethodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get contact method params
func (o *GetContactMethodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContactMethodID adds the contactMethodID to the get contact method params
func (o *GetContactMethodParams) WithContactMethodID(contactMethodID string) *GetContactMethodParams {
	o.SetContactMethodID(contactMethodID)
	return o
}

// SetContactMethodID adds the contactMethodId to the get contact method params
func (o *GetContactMethodParams) SetContactMethodID(contactMethodID string) {
	o.ContactMethodID = contactMethodID
}

// WithID adds the id to the get contact method params
func (o *GetContactMethodParams) WithID(id string) *GetContactMethodParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get contact method params
func (o *GetContactMethodParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetContactMethodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contact_method_id
	if err := r.SetPathParam("contact_method_id", o.ContactMethodID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
