// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/luqasn/go-pagerduty2/models"
)

// NewPutUsersIDContactMethodsContactMethodIDParams creates a new PutUsersIDContactMethodsContactMethodIDParams object
// with the default values initialized.
func NewPutUsersIDContactMethodsContactMethodIDParams() *PutUsersIDContactMethodsContactMethodIDParams {
	var ()
	return &PutUsersIDContactMethodsContactMethodIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutUsersIDContactMethodsContactMethodIDParamsWithTimeout creates a new PutUsersIDContactMethodsContactMethodIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutUsersIDContactMethodsContactMethodIDParamsWithTimeout(timeout time.Duration) *PutUsersIDContactMethodsContactMethodIDParams {
	var ()
	return &PutUsersIDContactMethodsContactMethodIDParams{

		timeout: timeout,
	}
}

// NewPutUsersIDContactMethodsContactMethodIDParamsWithContext creates a new PutUsersIDContactMethodsContactMethodIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutUsersIDContactMethodsContactMethodIDParamsWithContext(ctx context.Context) *PutUsersIDContactMethodsContactMethodIDParams {
	var ()
	return &PutUsersIDContactMethodsContactMethodIDParams{

		Context: ctx,
	}
}

// NewPutUsersIDContactMethodsContactMethodIDParamsWithHTTPClient creates a new PutUsersIDContactMethodsContactMethodIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutUsersIDContactMethodsContactMethodIDParamsWithHTTPClient(client *http.Client) *PutUsersIDContactMethodsContactMethodIDParams {
	var ()
	return &PutUsersIDContactMethodsContactMethodIDParams{
		HTTPClient: client,
	}
}

/*PutUsersIDContactMethodsContactMethodIDParams contains all the parameters to send to the API endpoint
for the put users ID contact methods contact method ID operation typically these are written to a http.Request
*/
type PutUsersIDContactMethodsContactMethodIDParams struct {

	/*ContactMethodID
	  The contact method ID on the user.

	*/
	ContactMethodID string
	/*ID*/
	ID string
	/*User
	  The user's contact method to be updated.

	*/
	User *models.PutUsersIDContactMethodsContactMethodIDParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) WithTimeout(timeout time.Duration) *PutUsersIDContactMethodsContactMethodIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) WithContext(ctx context.Context) *PutUsersIDContactMethodsContactMethodIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) WithHTTPClient(client *http.Client) *PutUsersIDContactMethodsContactMethodIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContactMethodID adds the contactMethodID to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) WithContactMethodID(contactMethodID string) *PutUsersIDContactMethodsContactMethodIDParams {
	o.SetContactMethodID(contactMethodID)
	return o
}

// SetContactMethodID adds the contactMethodId to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) SetContactMethodID(contactMethodID string) {
	o.ContactMethodID = contactMethodID
}

// WithID adds the id to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) WithID(id string) *PutUsersIDContactMethodsContactMethodIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) SetID(id string) {
	o.ID = id
}

// WithUser adds the user to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) WithUser(user *models.PutUsersIDContactMethodsContactMethodIDParamsBody) *PutUsersIDContactMethodsContactMethodIDParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the put users ID contact methods contact method ID params
func (o *PutUsersIDContactMethodsContactMethodIDParams) SetUser(user *models.PutUsersIDContactMethodsContactMethodIDParamsBody) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *PutUsersIDContactMethodsContactMethodIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contact_method_id
	if err := r.SetPathParam("contact_method_id", o.ContactMethodID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.User != nil {
		if err := r.SetBodyParam(o.User); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
