// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIncidentParams creates a new GetIncidentParams object
// with the default values initialized.
func NewGetIncidentParams() *GetIncidentParams {
	var ()
	return &GetIncidentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIncidentParamsWithTimeout creates a new GetIncidentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIncidentParamsWithTimeout(timeout time.Duration) *GetIncidentParams {
	var ()
	return &GetIncidentParams{

		timeout: timeout,
	}
}

// NewGetIncidentParamsWithContext creates a new GetIncidentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIncidentParamsWithContext(ctx context.Context) *GetIncidentParams {
	var ()
	return &GetIncidentParams{

		Context: ctx,
	}
}

// NewGetIncidentParamsWithHTTPClient creates a new GetIncidentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIncidentParamsWithHTTPClient(client *http.Client) *GetIncidentParams {
	var ()
	return &GetIncidentParams{
		HTTPClient: client,
	}
}

/*GetIncidentParams contains all the parameters to send to the API endpoint
for the get incident operation typically these are written to a http.Request
*/
type GetIncidentParams struct {

	/*ID
	  Either the id or number of the incident to retrieve.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get incident params
func (o *GetIncidentParams) WithTimeout(timeout time.Duration) *GetIncidentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get incident params
func (o *GetIncidentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get incident params
func (o *GetIncidentParams) WithContext(ctx context.Context) *GetIncidentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get incident params
func (o *GetIncidentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get incident params
func (o *GetIncidentParams) WithHTTPClient(client *http.Client) *GetIncidentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get incident params
func (o *GetIncidentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get incident params
func (o *GetIncidentParams) WithID(id string) *GetIncidentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get incident params
func (o *GetIncidentParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetIncidentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
