// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/luqasn/go-pagerduty2/models"
)

// NewSnoozeIncidentParams creates a new SnoozeIncidentParams object
// with the default values initialized.
func NewSnoozeIncidentParams() *SnoozeIncidentParams {
	var ()
	return &SnoozeIncidentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSnoozeIncidentParamsWithTimeout creates a new SnoozeIncidentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSnoozeIncidentParamsWithTimeout(timeout time.Duration) *SnoozeIncidentParams {
	var ()
	return &SnoozeIncidentParams{

		timeout: timeout,
	}
}

// NewSnoozeIncidentParamsWithContext creates a new SnoozeIncidentParams object
// with the default values initialized, and the ability to set a context for a request
func NewSnoozeIncidentParamsWithContext(ctx context.Context) *SnoozeIncidentParams {
	var ()
	return &SnoozeIncidentParams{

		Context: ctx,
	}
}

// NewSnoozeIncidentParamsWithHTTPClient creates a new SnoozeIncidentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSnoozeIncidentParamsWithHTTPClient(client *http.Client) *SnoozeIncidentParams {
	var ()
	return &SnoozeIncidentParams{
		HTTPClient: client,
	}
}

/*SnoozeIncidentParams contains all the parameters to send to the API endpoint
for the snooze incident operation typically these are written to a http.Request
*/
type SnoozeIncidentParams struct {

	/*From
	  The email address of the user making the request.

	*/
	From strfmt.Email
	/*ID*/
	ID string
	/*Payload*/
	Payload *models.SnoozeIncidentParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the snooze incident params
func (o *SnoozeIncidentParams) WithTimeout(timeout time.Duration) *SnoozeIncidentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the snooze incident params
func (o *SnoozeIncidentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the snooze incident params
func (o *SnoozeIncidentParams) WithContext(ctx context.Context) *SnoozeIncidentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the snooze incident params
func (o *SnoozeIncidentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the snooze incident params
func (o *SnoozeIncidentParams) WithHTTPClient(client *http.Client) *SnoozeIncidentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the snooze incident params
func (o *SnoozeIncidentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the snooze incident params
func (o *SnoozeIncidentParams) WithFrom(from strfmt.Email) *SnoozeIncidentParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the snooze incident params
func (o *SnoozeIncidentParams) SetFrom(from strfmt.Email) {
	o.From = from
}

// WithID adds the id to the snooze incident params
func (o *SnoozeIncidentParams) WithID(id string) *SnoozeIncidentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the snooze incident params
func (o *SnoozeIncidentParams) SetID(id string) {
	o.ID = id
}

// WithPayload adds the payload to the snooze incident params
func (o *SnoozeIncidentParams) WithPayload(payload *models.SnoozeIncidentParamsBody) *SnoozeIncidentParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the snooze incident params
func (o *SnoozeIncidentParams) SetPayload(payload *models.SnoozeIncidentParamsBody) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *SnoozeIncidentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param From
	if err := r.SetHeaderParam("From", o.From.String()); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
