// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/luqasn/go-pagerduty2/models"
)

// PutTeamsIDEscalationPoliciesEscalationPolicyIDReader is a Reader for the PutTeamsIDEscalationPoliciesEscalationPolicyID structure.
type PutTeamsIDEscalationPoliciesEscalationPolicyIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 402:
		result := NewPutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewPutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent creates a PutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent with default headers values
func NewPutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent() *PutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent {
	return &PutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent{}
}

/*PutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent handles this case with default header values.

The escalation policy was added to the team.
*/
type PutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent struct {
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /teams/{id}/escalation_policies/{escalation_policy_id}][%d] putTeamsIdEscalationPoliciesEscalationPolicyIdNoContent ", 204)
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest creates a PutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest with default headers values
func NewPutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest() *PutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest {
	return &PutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest{}
}

/*PutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest handles this case with default header values.

Caller provided invalid arguments. Please review the response for error details. Retrying with the same arguments will *not* work.
*/
type PutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest struct {
	Payload *models.Error
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /teams/{id}/escalation_policies/{escalation_policy_id}][%d] putTeamsIdEscalationPoliciesEscalationPolicyIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized creates a PutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized with default headers values
func NewPutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized() *PutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized {
	return &PutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized{}
}

/*PutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized handles this case with default header values.

Caller did not supply credentials or did not provide the correct credentials.
If you are using an API key, it may be invalid or your Authorization header may be malformed.

*/
type PutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized struct {
	Payload *models.Error
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /teams/{id}/escalation_policies/{escalation_policy_id}][%d] putTeamsIdEscalationPoliciesEscalationPolicyIdUnauthorized  %+v", 401, o.Payload)
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired creates a PutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired with default headers values
func NewPutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired() *PutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired {
	return &PutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired{}
}

/*PutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired handles this case with default header values.

Account does not have the abilities to perform the action. Please review the response for the required abilities.
You can also use the [Abilities API](#resource_Abilities) to determine what features are available to your account.

*/
type PutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired struct {
	Payload *models.Error
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired) Error() string {
	return fmt.Sprintf("[PUT /teams/{id}/escalation_policies/{escalation_policy_id}][%d] putTeamsIdEscalationPoliciesEscalationPolicyIdPaymentRequired  %+v", 402, o.Payload)
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDPaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden creates a PutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden with default headers values
func NewPutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden() *PutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden {
	return &PutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden{}
}

/*PutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden handles this case with default header values.

Caller is not authorized to view the requested resource.
While your authentication is valid, the authenticated user or token does not have permission to perform this action.

*/
type PutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden struct {
	Payload *models.Error
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden) Error() string {
	return fmt.Sprintf("[PUT /teams/{id}/escalation_policies/{escalation_policy_id}][%d] putTeamsIdEscalationPoliciesEscalationPolicyIdForbidden  %+v", 403, o.Payload)
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound creates a PutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound with default headers values
func NewPutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound() *PutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound {
	return &PutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound{}
}

/*PutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound handles this case with default header values.

The requested resource was not found.
*/
type PutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound struct {
	Payload *models.Error
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /teams/{id}/escalation_policies/{escalation_policy_id}][%d] putTeamsIdEscalationPoliciesEscalationPolicyIdNotFound  %+v", 404, o.Payload)
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests creates a PutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests with default headers values
func NewPutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests() *PutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests {
	return &PutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests{}
}

/*PutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests handles this case with default header values.

Too many requests have been made, the rate limit has been reached.
*/
type PutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests struct {
	Payload *models.Error
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /teams/{id}/escalation_policies/{escalation_policy_id}][%d] putTeamsIdEscalationPoliciesEscalationPolicyIdTooManyRequests  %+v", 429, o.Payload)
}

func (o *PutTeamsIDEscalationPoliciesEscalationPolicyIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
