// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicesParams creates a new GetServicesParams object
// with the default values initialized.
func NewGetServicesParams() *GetServicesParams {
	var (
		sortByDefault   = string("name")
		timeZoneDefault = string("UTC")
	)
	return &GetServicesParams{
		SortBy:   &sortByDefault,
		TimeZone: &timeZoneDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicesParamsWithTimeout creates a new GetServicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicesParamsWithTimeout(timeout time.Duration) *GetServicesParams {
	var (
		sortByDefault   = string("name")
		timeZoneDefault = string("UTC")
	)
	return &GetServicesParams{
		SortBy:   &sortByDefault,
		TimeZone: &timeZoneDefault,

		timeout: timeout,
	}
}

// NewGetServicesParamsWithContext creates a new GetServicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicesParamsWithContext(ctx context.Context) *GetServicesParams {
	var (
		sortByDefault   = string("name")
		timeZoneDefault = string("UTC")
	)
	return &GetServicesParams{
		SortBy:   &sortByDefault,
		TimeZone: &timeZoneDefault,

		Context: ctx,
	}
}

// NewGetServicesParamsWithHTTPClient creates a new GetServicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServicesParamsWithHTTPClient(client *http.Client) *GetServicesParams {
	var (
		sortByDefault   = string("name")
		timeZoneDefault = string("UTC")
	)
	return &GetServicesParams{
		SortBy:     &sortByDefault,
		TimeZone:   &timeZoneDefault,
		HTTPClient: client,
	}
}

/*GetServicesParams contains all the parameters to send to the API endpoint
for the get services operation typically these are written to a http.Request
*/
type GetServicesParams struct {

	/*Include
	  Array of additional details to include.

	*/
	Include []string
	/*Query
	  Filters the result, showing only the services whose name or service_key matches the query.

	*/
	Query *string
	/*SortBy
	  Used to specify the field you wish to sort the results on.

	*/
	SortBy *string
	/*TeamIds
	  An array of team IDs. Only results related to these teams will be returned. Account must have the `teams` ability to use this parameter.

	*/
	TeamIds []string
	/*TimeZone
	  Time zone in which dates in the result will be rendered.

	*/
	TimeZone *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get services params
func (o *GetServicesParams) WithTimeout(timeout time.Duration) *GetServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get services params
func (o *GetServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get services params
func (o *GetServicesParams) WithContext(ctx context.Context) *GetServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get services params
func (o *GetServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get services params
func (o *GetServicesParams) WithHTTPClient(client *http.Client) *GetServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get services params
func (o *GetServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInclude adds the include to the get services params
func (o *GetServicesParams) WithInclude(include []string) *GetServicesParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the get services params
func (o *GetServicesParams) SetInclude(include []string) {
	o.Include = include
}

// WithQuery adds the query to the get services params
func (o *GetServicesParams) WithQuery(query *string) *GetServicesParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the get services params
func (o *GetServicesParams) SetQuery(query *string) {
	o.Query = query
}

// WithSortBy adds the sortBy to the get services params
func (o *GetServicesParams) WithSortBy(sortBy *string) *GetServicesParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the get services params
func (o *GetServicesParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WithTeamIds adds the teamIds to the get services params
func (o *GetServicesParams) WithTeamIds(teamIds []string) *GetServicesParams {
	o.SetTeamIds(teamIds)
	return o
}

// SetTeamIds adds the teamIds to the get services params
func (o *GetServicesParams) SetTeamIds(teamIds []string) {
	o.TeamIds = teamIds
}

// WithTimeZone adds the timeZone to the get services params
func (o *GetServicesParams) WithTimeZone(timeZone *string) *GetServicesParams {
	o.SetTimeZone(timeZone)
	return o
}

// SetTimeZone adds the timeZone to the get services params
func (o *GetServicesParams) SetTimeZone(timeZone *string) {
	o.TimeZone = timeZone
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesInclude := o.Include

	joinedInclude := swag.JoinByFormat(valuesInclude, "multi")
	// query array param include[]
	if err := r.SetQueryParam("include[]", joinedInclude...); err != nil {
		return err
	}

	if o.Query != nil {

		// query param query
		var qrQuery string
		if o.Query != nil {
			qrQuery = *o.Query
		}
		qQuery := qrQuery
		if qQuery != "" {
			if err := r.SetQueryParam("query", qQuery); err != nil {
				return err
			}
		}

	}

	if o.SortBy != nil {

		// query param sort_by
		var qrSortBy string
		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {
			if err := r.SetQueryParam("sort_by", qSortBy); err != nil {
				return err
			}
		}

	}

	valuesTeamIds := o.TeamIds

	joinedTeamIds := swag.JoinByFormat(valuesTeamIds, "multi")
	// query array param team_ids[]
	if err := r.SetQueryParam("team_ids[]", joinedTeamIds...); err != nil {
		return err
	}

	if o.TimeZone != nil {

		// query param time_zone
		var qrTimeZone string
		if o.TimeZone != nil {
			qrTimeZone = *o.TimeZone
		}
		qTimeZone := qrTimeZone
		if qTimeZone != "" {
			if err := r.SetQueryParam("time_zone", qTimeZone); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
