// Code generated by go-swagger; DO NOT EDIT.

package api_reference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIReferenceParams creates a new GetAPIReferenceParams object
// with the default values initialized.
func NewGetAPIReferenceParams() *GetAPIReferenceParams {

	return &GetAPIReferenceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIReferenceParamsWithTimeout creates a new GetAPIReferenceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIReferenceParamsWithTimeout(timeout time.Duration) *GetAPIReferenceParams {

	return &GetAPIReferenceParams{

		timeout: timeout,
	}
}

// NewGetAPIReferenceParamsWithContext creates a new GetAPIReferenceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIReferenceParamsWithContext(ctx context.Context) *GetAPIReferenceParams {

	return &GetAPIReferenceParams{

		Context: ctx,
	}
}

// NewGetAPIReferenceParamsWithHTTPClient creates a new GetAPIReferenceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIReferenceParamsWithHTTPClient(client *http.Client) *GetAPIReferenceParams {

	return &GetAPIReferenceParams{
		HTTPClient: client,
	}
}

/*GetAPIReferenceParams contains all the parameters to send to the API endpoint
for the get API reference operation typically these are written to a http.Request
*/
type GetAPIReferenceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API reference params
func (o *GetAPIReferenceParams) WithTimeout(timeout time.Duration) *GetAPIReferenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API reference params
func (o *GetAPIReferenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API reference params
func (o *GetAPIReferenceParams) WithContext(ctx context.Context) *GetAPIReferenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API reference params
func (o *GetAPIReferenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API reference params
func (o *GetAPIReferenceParams) WithHTTPClient(client *http.Client) *GetAPIReferenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API reference params
func (o *GetAPIReferenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIReferenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
