// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EventTransformerAPIIntegration event transformer Api integration
// swagger:model EventTransformerApiIntegration
type EventTransformerAPIIntegration struct {
	APIBasedIntegration

	EventTransformerAPIIntegrationReference
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *EventTransformerAPIIntegration) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 APIBasedIntegration
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.APIBasedIntegration = aO0

	// AO1
	var aO1 EventTransformerAPIIntegrationReference
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.EventTransformerAPIIntegrationReference = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m EventTransformerAPIIntegration) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.APIBasedIntegration)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.EventTransformerAPIIntegrationReference)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this event transformer Api integration
func (m *EventTransformerAPIIntegration) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with APIBasedIntegration
	if err := m.APIBasedIntegration.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with EventTransformerAPIIntegrationReference
	if err := m.EventTransformerAPIIntegrationReference.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *EventTransformerAPIIntegration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventTransformerAPIIntegration) UnmarshalBinary(b []byte) error {
	var res EventTransformerAPIIntegration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
