// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExtensionSchemaReferenceAllOf1 extension schema reference all of1
// swagger:model extensionSchemaReferenceAllOf1
type ExtensionSchemaReferenceAllOf1 struct {

	// type
	// Enum: [extension_schema extension_schema_reference]
	Type string `json:"type,omitempty"`
}

// Validate validates this extension schema reference all of1
func (m *ExtensionSchemaReferenceAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var extensionSchemaReferenceAllOf1TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["extension_schema","extension_schema_reference"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		extensionSchemaReferenceAllOf1TypeTypePropEnum = append(extensionSchemaReferenceAllOf1TypeTypePropEnum, v)
	}
}

const (

	// ExtensionSchemaReferenceAllOf1TypeExtensionSchema captures enum value "extension_schema"
	ExtensionSchemaReferenceAllOf1TypeExtensionSchema string = "extension_schema"

	// ExtensionSchemaReferenceAllOf1TypeExtensionSchemaReference captures enum value "extension_schema_reference"
	ExtensionSchemaReferenceAllOf1TypeExtensionSchemaReference string = "extension_schema_reference"
)

// prop value enum
func (m *ExtensionSchemaReferenceAllOf1) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, extensionSchemaReferenceAllOf1TypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ExtensionSchemaReferenceAllOf1) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExtensionSchemaReferenceAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtensionSchemaReferenceAllOf1) UnmarshalBinary(b []byte) error {
	var res ExtensionSchemaReferenceAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
