// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetLogEntriesIDOKBody get log entries Id o k body
// swagger:model getLogEntriesIdOKBody
type GetLogEntriesIDOKBody struct {

	// log entry
	// Required: true
	LogEntry *LogEntry `json:"log_entry"`
}

// Validate validates this get log entries Id o k body
func (m *GetLogEntriesIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLogEntry(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetLogEntriesIDOKBody) validateLogEntry(formats strfmt.Registry) error {

	if err := validate.Required("log_entry", "body", m.LogEntry); err != nil {
		return err
	}

	if m.LogEntry != nil {
		if err := m.LogEntry.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("log_entry")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetLogEntriesIDOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetLogEntriesIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetLogEntriesIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
