// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KeynoteIntegrationAllOf2 keynote integration all of2
// swagger:model keynoteIntegrationAllOf2
type KeynoteIntegrationAllOf2 struct {

	// Specifies what severity levels will create a new open incident. It can be one of:
	//
	// - `critical`: Incidents are created when an alarm enters the critical state.
	// - `critical_or_warning`: Incidents are created when an alarm enters the critical **or** warning state.
	//
	// Enum: [critical critical_or_warning]
	SeverityFilter string `json:"severity_filter,omitempty"`
}

// Validate validates this keynote integration all of2
func (m *KeynoteIntegrationAllOf2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSeverityFilter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var keynoteIntegrationAllOf2TypeSeverityFilterPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["critical","critical_or_warning"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		keynoteIntegrationAllOf2TypeSeverityFilterPropEnum = append(keynoteIntegrationAllOf2TypeSeverityFilterPropEnum, v)
	}
}

const (

	// KeynoteIntegrationAllOf2SeverityFilterCritical captures enum value "critical"
	KeynoteIntegrationAllOf2SeverityFilterCritical string = "critical"

	// KeynoteIntegrationAllOf2SeverityFilterCriticalOrWarning captures enum value "critical_or_warning"
	KeynoteIntegrationAllOf2SeverityFilterCriticalOrWarning string = "critical_or_warning"
)

// prop value enum
func (m *KeynoteIntegrationAllOf2) validateSeverityFilterEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, keynoteIntegrationAllOf2TypeSeverityFilterPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *KeynoteIntegrationAllOf2) validateSeverityFilter(formats strfmt.Registry) error {

	if swag.IsZero(m.SeverityFilter) { // not required
		return nil
	}

	// value enum
	if err := m.validateSeverityFilterEnum("severity_filter", "body", m.SeverityFilter); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *KeynoteIntegrationAllOf2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KeynoteIntegrationAllOf2) UnmarshalBinary(b []byte) error {
	var res KeynoteIntegrationAllOf2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
