// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ListAbilitiesOKBody list abilities o k body
// swagger:model listAbilitiesOKBody
type ListAbilitiesOKBody struct {
	ListAbilitiesOKBodyAllOf0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ListAbilitiesOKBody) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ListAbilitiesOKBodyAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ListAbilitiesOKBodyAllOf0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ListAbilitiesOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ListAbilitiesOKBodyAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this list abilities o k body
func (m *ListAbilitiesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ListAbilitiesOKBodyAllOf0
	if err := m.ListAbilitiesOKBodyAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ListAbilitiesOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListAbilitiesOKBody) UnmarshalBinary(b []byte) error {
	var res ListAbilitiesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
