// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MaintenanceWindowReferenceAllOf1 maintenance window reference all of1
// swagger:model maintenanceWindowReferenceAllOf1
type MaintenanceWindowReferenceAllOf1 struct {

	// type
	// Enum: [maintenance_window maintenance_window_reference]
	Type string `json:"type,omitempty"`
}

// Validate validates this maintenance window reference all of1
func (m *MaintenanceWindowReferenceAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var maintenanceWindowReferenceAllOf1TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["maintenance_window","maintenance_window_reference"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		maintenanceWindowReferenceAllOf1TypeTypePropEnum = append(maintenanceWindowReferenceAllOf1TypeTypePropEnum, v)
	}
}

const (

	// MaintenanceWindowReferenceAllOf1TypeMaintenanceWindow captures enum value "maintenance_window"
	MaintenanceWindowReferenceAllOf1TypeMaintenanceWindow string = "maintenance_window"

	// MaintenanceWindowReferenceAllOf1TypeMaintenanceWindowReference captures enum value "maintenance_window_reference"
	MaintenanceWindowReferenceAllOf1TypeMaintenanceWindowReference string = "maintenance_window_reference"
)

// prop value enum
func (m *MaintenanceWindowReferenceAllOf1) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, maintenanceWindowReferenceAllOf1TypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *MaintenanceWindowReferenceAllOf1) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MaintenanceWindowReferenceAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MaintenanceWindowReferenceAllOf1) UnmarshalBinary(b []byte) error {
	var res MaintenanceWindowReferenceAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
