// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NagiosIntegrationReference nagios integration reference
// swagger:model NagiosIntegrationReference
type NagiosIntegrationReference struct {
	IntegrationReference

	NagiosIntegrationReferenceAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *NagiosIntegrationReference) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 IntegrationReference
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.IntegrationReference = aO0

	// AO1
	var aO1 NagiosIntegrationReferenceAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.NagiosIntegrationReferenceAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m NagiosIntegrationReference) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.IntegrationReference)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.NagiosIntegrationReferenceAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this nagios integration reference
func (m *NagiosIntegrationReference) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with IntegrationReference
	if err := m.IntegrationReference.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with NagiosIntegrationReferenceAllOf1
	if err := m.NagiosIntegrationReferenceAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NagiosIntegrationReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NagiosIntegrationReference) UnmarshalBinary(b []byte) error {
	var res NagiosIntegrationReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
