// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostEscalationPoliciesCreatedBody post escalation policies created body
// swagger:model postEscalationPoliciesCreatedBody
type PostEscalationPoliciesCreatedBody struct {

	// escalation policy
	// Required: true
	EscalationPolicy *EscalationPolicy `json:"escalation_policy"`
}

// Validate validates this post escalation policies created body
func (m *PostEscalationPoliciesCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEscalationPolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostEscalationPoliciesCreatedBody) validateEscalationPolicy(formats strfmt.Registry) error {

	if err := validate.Required("escalation_policy", "body", m.EscalationPolicy); err != nil {
		return err
	}

	if m.EscalationPolicy != nil {
		if err := m.EscalationPolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("escalation_policy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostEscalationPoliciesCreatedBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostEscalationPoliciesCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostEscalationPoliciesCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
