// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostUsersIDContactMethodsCreatedBody post users Id contact methods created body
// swagger:model postUsersIdContactMethodsCreatedBody
type PostUsersIDContactMethodsCreatedBody struct {

	// contact method
	// Required: true
	ContactMethod *ContactMethod `json:"contact_method"`
}

// Validate validates this post users Id contact methods created body
func (m *PostUsersIDContactMethodsCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContactMethod(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostUsersIDContactMethodsCreatedBody) validateContactMethod(formats strfmt.Registry) error {

	if err := validate.Required("contact_method", "body", m.ContactMethod); err != nil {
		return err
	}

	if m.ContactMethod != nil {
		if err := m.ContactMethod.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("contact_method")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostUsersIDContactMethodsCreatedBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostUsersIDContactMethodsCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostUsersIDContactMethodsCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
