// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostIncidentsIDNotesOKBody post incidents Id notes o k body
// swagger:model postIncidentsIdNotesOKBody
type PostIncidentsIDNotesOKBody struct {

	// note
	// Required: true
	Note *IncidentNote `json:"note"`
}

// Validate validates this post incidents Id notes o k body
func (m *PostIncidentsIDNotesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNote(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostIncidentsIDNotesOKBody) validateNote(formats strfmt.Registry) error {

	if err := validate.Required("note", "body", m.Note); err != nil {
		return err
	}

	if m.Note != nil {
		if err := m.Note.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("note")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostIncidentsIDNotesOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostIncidentsIDNotesOKBody) UnmarshalBinary(b []byte) error {
	var res PostIncidentsIDNotesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
