// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceReferenceAllOf1 service reference all of1
// swagger:model serviceReferenceAllOf1
type ServiceReferenceAllOf1 struct {

	// type
	// Enum: [service service_reference]
	Type string `json:"type,omitempty"`
}

// Validate validates this service reference all of1
func (m *ServiceReferenceAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var serviceReferenceAllOf1TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["service","service_reference"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serviceReferenceAllOf1TypeTypePropEnum = append(serviceReferenceAllOf1TypeTypePropEnum, v)
	}
}

const (

	// ServiceReferenceAllOf1TypeService captures enum value "service"
	ServiceReferenceAllOf1TypeService string = "service"

	// ServiceReferenceAllOf1TypeServiceReference captures enum value "service_reference"
	ServiceReferenceAllOf1TypeServiceReference string = "service_reference"
)

// prop value enum
func (m *ServiceReferenceAllOf1) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, serviceReferenceAllOf1TypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ServiceReferenceAllOf1) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceReferenceAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceReferenceAllOf1) UnmarshalBinary(b []byte) error {
	var res ServiceReferenceAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
