// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SQLMonitorIntegrationReferenceAllOf1 sql monitor integration reference all of1
// swagger:model sqlMonitorIntegrationReferenceAllOf1
type SQLMonitorIntegrationReferenceAllOf1 struct {

	// type
	// Enum: [sql_monitor_inbound_integration sql_monitor_inbound_integration_reference]
	Type string `json:"type,omitempty"`
}

// Validate validates this sql monitor integration reference all of1
func (m *SQLMonitorIntegrationReferenceAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var sqlMonitorIntegrationReferenceAllOf1TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["sql_monitor_inbound_integration","sql_monitor_inbound_integration_reference"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sqlMonitorIntegrationReferenceAllOf1TypeTypePropEnum = append(sqlMonitorIntegrationReferenceAllOf1TypeTypePropEnum, v)
	}
}

const (

	// SQLMonitorIntegrationReferenceAllOf1TypeSQLMonitorInboundIntegration captures enum value "sql_monitor_inbound_integration"
	SQLMonitorIntegrationReferenceAllOf1TypeSQLMonitorInboundIntegration string = "sql_monitor_inbound_integration"

	// SQLMonitorIntegrationReferenceAllOf1TypeSQLMonitorInboundIntegrationReference captures enum value "sql_monitor_inbound_integration_reference"
	SQLMonitorIntegrationReferenceAllOf1TypeSQLMonitorInboundIntegrationReference string = "sql_monitor_inbound_integration_reference"
)

// prop value enum
func (m *SQLMonitorIntegrationReferenceAllOf1) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, sqlMonitorIntegrationReferenceAllOf1TypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SQLMonitorIntegrationReferenceAllOf1) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SQLMonitorIntegrationReferenceAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SQLMonitorIntegrationReferenceAllOf1) UnmarshalBinary(b []byte) error {
	var res SQLMonitorIntegrationReferenceAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
