// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TeamReferenceAllOf1 team reference all of1
// swagger:model teamReferenceAllOf1
type TeamReferenceAllOf1 struct {

	// type
	// Enum: [team team_reference]
	Type string `json:"type,omitempty"`
}

// Validate validates this team reference all of1
func (m *TeamReferenceAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var teamReferenceAllOf1TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["team","team_reference"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		teamReferenceAllOf1TypeTypePropEnum = append(teamReferenceAllOf1TypeTypePropEnum, v)
	}
}

const (

	// TeamReferenceAllOf1TypeTeam captures enum value "team"
	TeamReferenceAllOf1TypeTeam string = "team"

	// TeamReferenceAllOf1TypeTeamReference captures enum value "team_reference"
	TeamReferenceAllOf1TypeTeamReference string = "team_reference"
)

// prop value enum
func (m *TeamReferenceAllOf1) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, teamReferenceAllOf1TypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *TeamReferenceAllOf1) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TeamReferenceAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeamReferenceAllOf1) UnmarshalBinary(b []byte) error {
	var res TeamReferenceAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
